#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# This file contains selected Kconfig options for the application.

# logging
CONFIG_LOG=y
CONFIG_NCS_NXP_DISCOVERY_LOOP_SAMPLE_LOG_LEVEL_INF=y

# use NFC NXP driver HAL
CONFIG_NFC_DRIVER_NXP=y
CONFIG_NFC_DRIVER_STM=n
CONFIG_PN5190_DRV=y
CONFIG_NFC_NXP_PAL_I14443P3A=y
CONFIG_NFC_NXP_PAL_I14443P4A=y
CONFIG_NFC_NXP_PAL_I14443P4=y

CONFIG_MAIN_STACK_SIZE=4096

# Discovery loop profile configuration (enabled by default via Kconfig)
# CONFIG_NCS_NXP_DISCOVERY_LOOP_DISC_CONFIG=n

# Low power card detection (enabled by default via Kconfig)
# CONFIG_NCS_NXP_DISCOVERY_LOOP_LPCD=n
