CONFIG_ALIRO_AT_MODULE=y
CONFIG_REBOOT=y
CONFIG_PM_EXTERNAL_FLASH_MCUBOOT_SECONDARY=n
CONFIG_DOOR_LOCK_EXTERNAL_NVS=n
CONFIG_DOOR_LOCK_INTERNAL_ZMS=y
#CONFIG_DOOR_LOCK_APP_LOG_LEVEL_DBG=y
#CONFIG_DOOR_LOCK_INTERNAL_ZMS_LOG_LEVEL_DBG=y
CONFIG_NFC_DRIVER_STM=n
CONFIG_NFC_DRIVER_NXP=y